# Use an official node runtime as a parent image
FROM node:alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# Install dependencies
COPY package.json /app/
RUN npm install --silent --save-dev dotenv
RUN npm install react-scripts@3.0.1 -g --silent

# Add rest of the client code
COPY . /app/

EXPOSE 3000

CMD ["npm", "start"]