version: "3.2"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    stdin_open: true
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    command: npm start
