version: "3.2"
services:
  backend:
    build:
      context: ./DoctorsOffice
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
  frontend:
    stdin_open: true
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    command: npm start
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=DoctorsOfficeDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432"
